name: Main Diffaction workflow

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build linting containers
      run: docker build -t ${{ inputs.service-name }}-lint -f docker/Dockerfile.lint .

    - name: Run linting
      run: docker run --rm ${{ inputs.service-name }}-lint